// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.11.4
// source: cdh.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsealSecretInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret []byte `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *UnsealSecretInput) Reset() {
	*x = UnsealSecretInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsealSecretInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealSecretInput) ProtoMessage() {}

func (x *UnsealSecretInput) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealSecretInput.ProtoReflect.Descriptor instead.
func (*UnsealSecretInput) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{0}
}

func (x *UnsealSecretInput) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UnsealSecretOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
}

func (x *UnsealSecretOutput) Reset() {
	*x = UnsealSecretOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsealSecretOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealSecretOutput) ProtoMessage() {}

func (x *UnsealSecretOutput) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealSecretOutput.ProtoReflect.Descriptor instead.
func (*UnsealSecretOutput) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{1}
}

func (x *UnsealSecretOutput) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type GetResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourcePath string `protobuf:"bytes,1,opt,name=ResourcePath,proto3" json:"ResourcePath,omitempty"`
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceRequest) GetResourcePath() string {
	if x != nil {
		return x.ResourcePath
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource []byte `protobuf:"bytes,1,opt,name=Resource,proto3" json:"Resource,omitempty"`
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceResponse) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

type SecureMountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver        string   `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverOptions []string `protobuf:"bytes,2,rep,name=driver_options,json=driverOptions,proto3" json:"driver_options,omitempty"`
	Source        string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Fstype        string   `protobuf:"bytes,4,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Options       []string `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	MountPoint    string   `protobuf:"bytes,6,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
}

func (x *SecureMountRequest) Reset() {
	*x = SecureMountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecureMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountRequest) ProtoMessage() {}

func (x *SecureMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountRequest.ProtoReflect.Descriptor instead.
func (*SecureMountRequest) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{4}
}

func (x *SecureMountRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *SecureMountRequest) GetDriverOptions() []string {
	if x != nil {
		return x.DriverOptions
	}
	return nil
}

func (x *SecureMountRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SecureMountRequest) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *SecureMountRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SecureMountRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type SecureMountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MountPath string `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
}

func (x *SecureMountResponse) Reset() {
	*x = SecureMountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecureMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountResponse) ProtoMessage() {}

func (x *SecureMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountResponse.ProtoReflect.Descriptor instead.
func (*SecureMountResponse) Descriptor() ([]byte, []int) {
	return file_cdh_proto_rawDescGZIP(), []int{5}
}

func (x *SecureMountResponse) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

var File_cdh_proto protoreflect.FileDescriptor

var file_cdh_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x64, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x64, 0x68,
	0x22, 0x2b, 0x0a, 0x11, 0x55, 0x6e, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x32, 0x0a,
	0x12, 0x55, 0x6e, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x31, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xbe,
	0x01, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x25, 0x0a,
	0x0e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x73, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22,
	0x34, 0x0a, 0x13, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x32, 0x58, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c,
	0x55, 0x6e, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x63,
	0x64, 0x68, 0x2e, 0x55, 0x6e, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x64, 0x68, 0x2e, 0x55, 0x6e, 0x73, 0x65, 0x61,
	0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x32,
	0x58, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x64, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x63, 0x64, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x58, 0x0a, 0x12, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x0b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17,
	0x2e, 0x63, 0x64, 0x68, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x64, 0x68, 0x2e, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cdh_proto_rawDescOnce sync.Once
	file_cdh_proto_rawDescData = file_cdh_proto_rawDesc
)

func file_cdh_proto_rawDescGZIP() []byte {
	file_cdh_proto_rawDescOnce.Do(func() {
		file_cdh_proto_rawDescData = protoimpl.X.CompressGZIP(file_cdh_proto_rawDescData)
	})
	return file_cdh_proto_rawDescData
}

var file_cdh_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cdh_proto_goTypes = []interface{}{
	(*UnsealSecretInput)(nil),   // 0: cdh.UnsealSecretInput
	(*UnsealSecretOutput)(nil),  // 1: cdh.UnsealSecretOutput
	(*GetResourceRequest)(nil),  // 2: cdh.GetResourceRequest
	(*GetResourceResponse)(nil), // 3: cdh.GetResourceResponse
	(*SecureMountRequest)(nil),  // 4: cdh.SecureMountRequest
	(*SecureMountResponse)(nil), // 5: cdh.SecureMountResponse
}
var file_cdh_proto_depIdxs = []int32{
	0, // 0: cdh.SealedSecretService.UnsealSecret:input_type -> cdh.UnsealSecretInput
	2, // 1: cdh.GetResourceService.GetResource:input_type -> cdh.GetResourceRequest
	4, // 2: cdh.SecureMountService.SecureMount:input_type -> cdh.SecureMountRequest
	1, // 3: cdh.SealedSecretService.UnsealSecret:output_type -> cdh.UnsealSecretOutput
	3, // 4: cdh.GetResourceService.GetResource:output_type -> cdh.GetResourceResponse
	5, // 5: cdh.SecureMountService.SecureMount:output_type -> cdh.SecureMountResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cdh_proto_init() }
func file_cdh_proto_init() {
	if File_cdh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cdh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsealSecretInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsealSecretOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecureMountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecureMountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cdh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cdh_proto_goTypes,
		DependencyIndexes: file_cdh_proto_depIdxs,
		MessageInfos:      file_cdh_proto_msgTypes,
	}.Build()
	File_cdh_proto = out.File
	file_cdh_proto_rawDesc = nil
	file_cdh_proto_goTypes = nil
	file_cdh_proto_depIdxs = nil
}
